language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database timesheets;'
script:
  - make test
  - python manage.py test
