language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install codecov
before_script:
  - psql -c 'create database timesheets;' -U postgres
script:
  - make coverage
after_success:
  - codecov
