# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_send_date', models.DateField()),
                ('next_send_date', models.DateField()),
                ('hours', models.IntegerField()),
                ('unit_of_organisation', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=200)),
            ],
        ),
    ]
