# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-30 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='surname',
        ),
    ]
