# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-20 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20180430_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='first_send_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_send_date',
        ),
    ]
